"""EMIT (YAML/classic band) — branch IR -> HA automation YAML via the Jinja2
band templates (COMPILER_SPEC §3.3). One automation per top-level statement
(§2.5 point 4 TCP scoping).

Session-3 coverage: if-branches with else / else-if / nested ifs (emitted as
HA's native if/then/else action blocks), `every` timers (time / time_pattern
triggers), trigger promotion for condition-only pistons, equality + between +
numeric comparisons with any/all aggregation, the $time is_between window
(HA time condition), and command data params (setLevel/setColor via
command_maps.json $-tokens). TCP-default branches emit mode: restart +
auxiliary cancel-triggers gated by `condition: trigger`; `queued` (Jeremy's
default) governs where TCP doesn't force restart."""

import json as _json_mod
import re
from pathlib import Path


def _json_dumps(v):
    return _json_mod.dumps(v)

from jinja2 import Environment, FileSystemLoader

from .analyze import analyze
from .errors import NotYetImplemented
from .expression import JinjaTranspiler
from .resolve import Resolver

_BAND_DIR = Path(__file__).resolve().parent.parent.parent / "templates" / "compiler" / "yaml" / "classic"
_env = Environment(loader=FileSystemLoader(str(_BAND_DIR)), trim_blocks=False, lstrip_blocks=False)

# the piston currently being compiled — the text/expression helpers need its
# variable declarations, and threading it through every call site would touch
# a dozen signatures for one read-only lookup.
_PISTON: dict = {"cur": None}

_NUMERIC_OPS = {"is_less_than": "<", "is_less_than_or_equal_to": "<=",
                "is_greater_than": ">", "is_greater_than_or_equal_to": ">="}
_EQUALITY_OPS = {"is": "==", "is_equal_to": "==",
                 "is_not": "!=", "is_not_equal_to": "!="}


def _hex_rgb(value):
    v = str(value)
    if not v.startswith("#"):
        import json as _json
        maps = _json.load(open(_BAND_DIR / "value_maps.json", encoding="utf-8"))
        v = maps.get("color_names", {}).get(v.strip().lower(), v)
    v = v.lstrip("#")
    try:
        return [int(v[0:2], 16), int(v[2:4], 16), int(v[4:6], 16)]
    except ValueError:
        raise NotYetImplemented(
            f"colour value {value!r} isn't a hex code or a known colour name — "
            f"add it to value_maps.json color_names")


def _mode_value(kind):
    """webCoRE mode word -> HA mode word, via value_maps.mode_values."""
    def xform(v):
        import json as _json
        maps = _json.load(open(_BAND_DIR / "value_maps.json", encoding="utf-8"))
        table = maps.get("mode_values", {}).get(kind, {})
        key = str(v).strip()
        return table.get(key, table.get(key.lower(), v))
    return xform


_PARAM_TRANSFORMS = {"hex_rgb": _hex_rgb,
                     # webCoRE volume/level 0-100 -> HA volume_level 0.0-1.0
                     "pct_float": lambda v: round(float(v) / 100.0, 2),
                     # hue/saturation are 0-100 in webCoRE; HA wants [hue0-360, sat0-100]
                     "hue_hs": lambda v: [round(float(v) * 3.6, 1), 100],
                     "sat_hs": lambda v: [0, round(float(v), 1)],
                     "hvac_mode": _mode_value("hvac_mode"),
                     "fan_mode": _mode_value("fan_mode"),
                     "speed_pct": _mode_value("fan_speed")}


def _delay_hms(params: list) -> str:
    p = params[0] if params else {}
    n = p.get("c", 0)
    unit = p.get("vt", "s")
    seconds = {"s": n, "m": n * 60, "h": n * 3600}.get(unit, n)
    return f"{seconds // 3600:02d}:{(seconds % 3600) // 60:02d}:{seconds % 60:02d}"


def _minutes_hms(minutes: int) -> str:
    return f"{minutes // 60:02d}:{minutes % 60:02d}:00"


def _duration_hms(op) -> str | None:
    """The `to` operand on stays/remains/was comparisons — a hold time.
    Returns HH:MM:SS or None when it isn't a fixed number."""
    if not isinstance(op, dict):
        return None
    n = op.get("c")
    if not isinstance(n, (int, float)) or isinstance(n, bool):
        return None
    secs = int(n * {"s": 1, "m": 60, "h": 3600, "d": 86400}.get(op.get("vt", "s"), 1))
    return f"{secs // 3600:02d}:{(secs % 3600) // 60:02d}:{secs % 60:02d}"


def _is_number(v) -> bool:
    return isinstance(v, (int, float)) and not isinstance(v, bool)


def compile_yaml(piston: dict, piston_id: str, piston_name: str,
                 resolution_map: dict, globals_map: dict | None = None) -> dict:
    """Returns {"target": "yaml", "yaml": str, "reasons": [], "auto_ids": [...]}.
    Routing lives in the package dispatcher (__init__.compile_piston) — a
    NotYetImplemented raised here falls through to the PyScript band there."""
    _PISTON["cur"] = piston
    branches = analyze(piston, piston_id, piston_name)
    resolver = Resolver(piston, resolution_map, globals_map)
    blocks = []
    auto_ids = []
    header = (f"# Generated by PistonCore — piston \"{piston_name}\" ({piston_id})\n"
              f"# DO NOT EDIT — changes are overwritten on recompile. Template band: yaml/classic\n")

    # A piston that subscribes to nothing is not an automation — it is a
    # runnable sequence. HA's word for that is a script, which is also what
    # webCoRE's Test button and executePiston target
    # (HA_YAML_COMPILER_RESEARCH §2).
    if _has_no_subscriptions(branches):
        return _compile_script(branches, resolver, piston_id, piston_name, header)

    try:
        for br in branches:
            _emit_branch(br, resolver, piston_id, piston_name, blocks, auto_ids)
    except _NoSubscriptions:
        # promotion found nothing subscribable after all — same conclusion,
        # reached later: this piston is a script.
        return _compile_script(branches, resolver, piston_id, piston_name, header)
    except Exception as exc:
        # Half-finished output holds clues to compiler bugs (Jeremy, 2026-07-18:
        # the compiler, not the battle-tested webCoRE JSON, is the likely
        # suspect) — hand back whatever was built before dying so deploy can
        # preserve it in the debug folder.
        exc.partial_yaml = header + "\n".join(blocks) + "\n" if blocks else None
        raise

    return {"target": "yaml", "yaml": header + "\n".join(blocks) + "\n", "reasons": [],
            "auto_ids": auto_ids}


class _NoSubscriptions(Exception):
    """Internal signal: nothing in this piston can wake it, so it compiles to
    a script rather than an automation."""


def _has_no_subscriptions(branches: list) -> bool:
    """True when nothing in this piston can wake it: no trigger comparisons,
    no timers, and no conditions that promotion could subscribe to."""
    for br in branches:
        if br["kind"] == "timer" or br["triggers"]:
            return False
        for cond in br["conditions"]:
            if cond.get("lo_type") == "p" and cond.get("devices"):
                return False
    return True


def _compile_script(branches: list, resolver: Resolver, piston_id: str,
                    piston_name: str, header: str) -> dict:
    """Emit the whole piston as one HA script."""
    ctx = {"piston_id": piston_id, "piston_name": piston_name, "stmt_id": None}
    actions = []
    for br in branches:
        body = _resolve_actions(br["then"], resolver, ctx)
        cond_nodes = [_condition(c, resolver, ctx) for c in br["conditions"]]
        els = _resolve_actions(br["else"], resolver, ctx)
        if cond_nodes:
            actions.append({"kind": "if", "conditions": cond_nodes,
                            "then": body, "else": els})
        else:
            actions.extend(body)
    script_id = f"pistoncore_{piston_id}"
    block = _env.get_template("script.yaml.j2").render(
        script_id=script_id,
        alias=f"PistonCore: {piston_name}",
        mode="restart" if (branches and branches[0]["tcp"] == "c") else "queued",
        actions=actions,
    )
    return {"target": "yaml", "kind": "script", "yaml": header + block,
            "reasons": [], "auto_ids": [], "script_ids": [script_id],
            "unresolved": resolver.unresolved}


# ── conditions ──────────────────────────────────────────────────────────────

_SUN_EVENTS = {"sunrise": "sunrise", "sunset": "sunset"}


def _sun_bound(cond, which):
    """A time bound that is a sun preset (sunrise/sunset), possibly with the
    piston's own offset. Returns (event, offset_hms) or None."""
    preset = cond.get("value_preset") if which == 1 else cond.get("value2_preset")
    if not preset:
        expr = cond.get("value_expr") if which == 1 else cond.get("value2_expr")
        if isinstance(expr, str) and expr.strip().lower().lstrip("$") in ("sunrise", "sunset"):
            preset = expr.strip().lower().lstrip("$")
    if not preset:
        return None
    key = str(preset).strip().lower()
    for name, event in _SUN_EVENTS.items():
        if key.startswith(name):
            return event
    return None


def _condition(cond: dict, resolver: Resolver, ctx: dict) -> dict:
    """Condition IR node -> template/time/sun condition dict for the template."""
    co = cond["co"]

    # nested condition group -> HA's and/or condition blocks
    if co == "_group":
        kids = [_condition(c, resolver, ctx) for c in cond["children"]]
        return {"kind": "or" if cond["group_op"] == "or" else "and",
                "conditions": kids}

    if cond.get("lo_type") == "v":
        var = cond.get("lo_var")
        # $time between-window -> HA's native time condition
        if (var == "time" and co == "is_between"
                and cond.get("value_vt") == "time" and cond.get("value2_vt") == "time"
                and _is_number(cond["value"]) and _is_number(cond["value2"])):
            return {"kind": "time",
                    "after": _minutes_hms(int(cond["value"])),
                    "before": _minutes_hms(int(cond["value2"]))}
        # $time between sunset and X (or any sun preset bound) -> sun condition
        if var == "time" and co in ("is_between", "is_not_between"):
            a_sun, b_sun = _sun_bound(cond, 1), _sun_bound(cond, 2)
            if a_sun or b_sun:
                node = {"kind": "sun"}
                if a_sun:
                    node["after"] = a_sun
                elif _is_number(cond["value"]):
                    node["after_time"] = _minutes_hms(int(cond["value"]))
                if b_sun:
                    node["before"] = b_sun
                elif _is_number(cond["value2"]):
                    node["before_time"] = _minutes_hms(int(cond["value2"]))
                if node.get("after_time") or node.get("before_time"):
                    # mixed clock+sun bound: HA can't express it in one node —
                    # a template using the sun entity's next event does
                    return _sun_mixed_template(node, cond)
                return node
        # $time before/after -> HA time condition (one-sided window)
        if var == "time" and co in ("is_before", "is_after") and _is_number(cond["value"]):
            hms = _minutes_hms(int(cond["value"]))
            return {"kind": "time", "before" if co == "is_before" else "after": hms}
        # entity-backed system variables ($alarmSystemStatus, $mode, ...)
        sysent = resolver.system_entity(var) if var else None
        if sysent and co in _EQUALITY_OPS:
            mapped = resolver.system_value(var, cond["value"])
            return {"kind": "template", "template":
                    f"{{{{ states('{sysent}') {_EQUALITY_OPS[co]} '{mapped}' }}}}"}
        if var in ("time", "datetime") and co in ("is_between", "is_not_between"):
            # a computed bound (sunrise variable, expression) — compare
            # minutes-since-midnight in a template rather than giving up
            jt = _jinja(resolver, ctx, _PISTON.get("cur"))

            def _bound(num, expr):
                if _is_number(num):
                    return str(int(num))
                if not expr:
                    raise NotYetImplemented("time bound is not expressible", **ctx)
                return ("((" + jt.transpile_operand({"e": str(expr).rstrip("; ")})
                        + ") | int)")

            lo_b = _bound(cond.get("value"), cond.get("value_expr"))
            hi_b = _bound(cond.get("value2"), cond.get("value2_expr"))
            mins = "(now().hour * 60 + now().minute)"
            body = (f"({lo_b} <= {mins} <= {hi_b}) if {lo_b} <= {hi_b} "
                    f"else ({mins} >= {lo_b} or {mins} <= {hi_b})")
            if co == "is_not_between":
                body = "not (" + body + ")"
            return {"kind": "template", "template": "{{ " + body + " }}"}
        raise NotYetImplemented(
            f"condition on variable '{var}' ({co}) requires PyScript", **ctx)

    entities = resolver.entities_for_attr(cond["devices"], cond["attr"], ctx)
    joiner = " and " if cond.get("aggregation") == "all" else " or "

    if co in _NUMERIC_OPS:
        op = _NUMERIC_OPS[co]
        # fail-closed default: unavailable sensor -> condition false (fixture rule)
        parts = [f"states('{e}') | float(default=1.0e9) {op} {cond['value']}"
                 for e in entities]
    elif co == "is_between" and _is_number(cond["value"]) and _is_number(cond["value2"]):
        parts = [f"{cond['value']} <= states('{e}') | float(default=1.0e9) <= {cond['value2']}"
                 for e in entities]
    elif co in _EQUALITY_OPS:
        op = _EQUALITY_OPS[co]
        value = cond["value"]
        if _is_number(value):
            parts = [f"states('{e}') | float(default=1.0e9) {op} {value}" for e in entities]
        else:
            mapped = resolver.ha_state_value(cond["attr"], value)
            parts = [f"states('{e}') {op} '{mapped}'" for e in entities]
    elif co in ("is_any_of", "is_not_any_of", "is_any"):
        vals = cond["value"] if isinstance(cond["value"], list) else [cond["value"]]
        mapped = [str(resolver.ha_state_value(cond["attr"], v)) for v in vals]
        neg = "not " if co == "is_not_any_of" else ""
        parts = [f"{neg}states('{e}') in {mapped!r}" for e in entities]
    elif co in ("is_even", "is_odd"):
        want = 0 if co == "is_even" else 1
        parts = [f"states('{e}') | int(default=-1) % 2 == {want}" for e in entities]
    elif co == "is_not_between":
        parts = [f"not ({cond['value']} <= states('{e}') | float(default=1.0e9) "
                 f"<= {cond['value2']})" for e in entities]
    elif co in ("is_inside_of_range",):
        parts = [f"{cond['value']} <= states('{e}') | float(default=1.0e9) "
                 f"<= {cond['value2']}" for e in entities]
    elif co in ("is_outside_of_range",):
        parts = [f"not ({cond['value']} <= states('{e}') | float(default=1.0e9) "
                 f"<= {cond['value2']})" for e in entities]
    elif co in ("stays_greater_than", "stays_greater_than_or_equal_to",
                "stays_less_than", "stays_less_than_or_equal_to",
                "remains_above", "remains_below"):
        OPS = {"stays_greater_than": ">", "stays_greater_than_or_equal_to": ">=",
               "stays_less_than": "<", "stays_less_than_or_equal_to": "<=",
               "remains_above": ">", "remains_below": "<"}
        op = OPS[co]
        hold = _duration_hms(cond.get("duration")) or "00:00:00"
        h, m, sec = (int(x) for x in hold.split(":"))
        secs = h * 3600 + m * 60 + sec
        parts = [f"(states('{e}') | float(default=1.0e9) {op} {cond['value']} and "
                 f"(as_timestamp(now()) - as_timestamp(states.{e}.last_changed)) >= {secs})"
                 for e in entities]
    elif co in ("stays", "stays_equal_to", "stays_any_of", "was", "was_not"):
        vals = cond["value"] if isinstance(cond["value"], list) else [cond["value"]]
        mapped = [str(resolver.ha_state_value(cond["attr"], v)) for v in vals]
        hold = _duration_hms(cond.get("duration")) or "00:00:00"
        h, m, sec = (int(x) for x in hold.split(":"))
        secs = h * 3600 + m * 60 + sec
        neg = "not " if co == "was_not" else ""
        parts = [f"({neg}states('{e}') in {mapped!r} and "
                 f"(as_timestamp(now()) - as_timestamp(states.{e}.last_changed)) >= {secs})"
                 for e in entities]
    elif co in ("changes_to", "gets", "arrives", "stays", "stays_equal_to"):
        mapped = resolver.ha_state_value(cond["attr"], cond["value"])
        parts = [f"states('{e}') == '{mapped}'" for e in entities]
    elif co in ("changes_away_from", "stays_away_from"):
        mapped = resolver.ha_state_value(cond["attr"], cond["value"])
        parts = [f"states('{e}') != '{mapped}'" for e in entities]
    elif co in ("changes_to_any_of", "stays_any_of"):
        vals = cond["value"] if isinstance(cond["value"], list) else [cond["value"]]
        mapped = [str(resolver.ha_state_value(cond["attr"], v)) for v in vals]
        parts = [f"states('{e}') in {mapped!r}" for e in entities]
    elif co in ("changes", "changed"):
        parts = ["true"]      # the automation only ran because something changed
    elif co in ("rises_above", "rises", "rises_to_or_above"):
        parts = [f"states('{e}') | float(default=-1.0e9) > {cond['value']}"
                 for e in entities]
    elif co in ("drops_below", "drops", "drops_to_or_below"):
        parts = [f"states('{e}') | float(default=1.0e9) < {cond['value']}"
                 for e in entities]
    elif co in ("was_greater_than", "was_greater_than_or_equal_to",
                "was_less_than", "was_less_than_or_equal_to"):
        OPS = {"was_greater_than": ">", "was_greater_than_or_equal_to": ">=",
               "was_less_than": "<", "was_less_than_or_equal_to": "<="}
        parts = [f"states('{e}') | float(default=1.0e9) {OPS[co]} {cond['value']}"
                 for e in entities]
    elif co in ("was_equal_to", "was_any_of"):
        vals = cond["value"] if isinstance(cond["value"], list) else [cond["value"]]
        mapped = [str(resolver.ha_state_value(cond["attr"], v)) for v in vals]
        parts = [f"states('{e}') in {mapped!r}" for e in entities]
    elif co == "is_different_than":
        mapped = resolver.ha_state_value(cond["attr"], cond["value"])
        parts = [f"states('{e}') != '{mapped}'" for e in entities]
    else:
        raise NotYetImplemented(f"condition comparison '{co}' not compiled yet", **ctx)

    body = parts[0] if len(parts) == 1 else "(" + joiner.join(parts) + ")"
    return {"kind": "template", "template": "{{ " + body + " }}"}


def _sun_mixed_template(node: dict, cond: dict) -> dict:
    """One bound is a sun event, the other a clock time — HA's sun condition
    can't mix them, so compare against the sun entity's timestamp attribute."""
    parts = []
    if node.get("after"):
        parts.append(f"now() >= (state_attr('sun.sun', 'next_{node['after']}') | "
                     f"as_datetime | as_local)")
    if node.get("before"):
        parts.append(f"now() <= (state_attr('sun.sun', 'next_{node['before']}') | "
                     f"as_datetime | as_local)")
    if node.get("after_time"):
        parts.append(f"now().strftime('%H:%M:%S') >= '{node['after_time']}'")
    if node.get("before_time"):
        parts.append(f"now().strftime('%H:%M:%S') <= '{node['before_time']}'")
    return {"kind": "template", "template": "{{ " + " and ".join(parts) + " }}"}


# ── triggers ────────────────────────────────────────────────────────────────

def _trigger(trig: dict, resolver: Resolver, ctx: dict, trig_id=None) -> dict:
    co = trig["co"]
    if trig.get("lo_type") == "v":
        var = trig.get("lo_var")
        # "happens daily at ..." -> HA time trigger, or sun trigger when the
        # time is a sunrise/sunset preset
        if var == "time" and trig["co"] in ("happens_daily_at", "happens_at"):
            sun_ev = _sun_bound(trig, 1)
            if sun_ev:
                return {"kind": "sun", "event": sun_ev, "id": trig_id}
            if _is_number(trig["value"]):
                return {"kind": "time", "at": _minutes_hms(int(trig["value"])),
                        "id": trig_id}
        sysent = resolver.system_entity(var) if var else None
        if sysent and co in ("executes", "changes_to_any_of", "is_any_of"):
            raw = trig["value"]
            vals = raw if isinstance(raw, list) else [raw]
            mapped = [str(resolver.system_value(var, v)) for v in vals]
            return {"kind": "state", "entities": [sysent],
                    "to": mapped if len(mapped) > 1 else mapped[0], "id": trig_id}
        if sysent and co == "changes_to":
            return {"kind": "state", "entities": [sysent],
                    "to": resolver.system_value(var, trig["value"]), "id": trig_id}
        if sysent and co == "changes":
            return {"kind": "state", "entities": [sysent], "id": trig_id}
        raise NotYetImplemented(
            f"trigger on variable '{var}' ({co}) requires PyScript", **ctx)
    entities = resolver.entities_for_attr(trig["devices"], trig["attr"], ctx)
    attr, value = trig["attr"], trig["value"]
    hold = _duration_hms(trig.get("duration"))

    def mapped(v):
        return resolver.ha_state_value(attr, v)

    def as_list(v):
        return [mapped(x) for x in v] if isinstance(v, list) else [mapped(v)]

    # ── state (equality) family ──
    if co in ("changes_to", "gets", "arrives"):
        return {"kind": "state", "entities": entities, "to": mapped(value), "id": trig_id}
    if co == "changes":
        return {"kind": "state", "entities": entities, "id": trig_id}
    if co == "changes_away_from":
        return {"kind": "state", "entities": entities, "from": mapped(value), "id": trig_id}
    if co == "changes_to_any_of":
        return {"kind": "state", "entities": entities, "to": as_list(value), "id": trig_id}
    if co == "changes_away_from_any_of":
        return {"kind": "state", "entities": entities, "from": as_list(value), "id": trig_id}
    # "stays X for N" -> HA's native `for:` on a state trigger
    if co in ("stays", "stays_equal_to") and hold:
        return {"kind": "state", "entities": entities, "to": mapped(value),
                "for": hold, "id": trig_id}
    if co == "stays_any_of" and hold:
        return {"kind": "state", "entities": entities, "to": as_list(value),
                "for": hold, "id": trig_id}
    if co in ("stays_away_from", "stays_different_than") and hold:
        return {"kind": "state", "entities": entities, "from": mapped(value),
                "for": hold, "id": trig_id}
    if co == "stays_unchanged" and hold:
        return {"kind": "state", "entities": entities, "for": hold, "id": trig_id}

    # ── numeric family ──
    NUM_ABOVE = ("rises_above", "rises", "rises_to_or_above", "becomes_greater_than")
    NUM_BELOW = ("drops_below", "drops", "drops_to_or_below", "becomes_less_than")
    if co in NUM_ABOVE:
        return {"kind": "numeric_state", "entities": entities,
                "above": value, "id": trig_id}
    if co in NUM_BELOW:
        return {"kind": "numeric_state", "entities": entities,
                "below": value, "id": trig_id}
    if co in ("enters_range", "remains_inside_of_range", "stays_inside_of_range"):
        node = {"kind": "numeric_state", "entities": entities,
                "above": value, "below": trig.get("value2"), "id": trig_id}
        if hold and co != "enters_range":
            node["for"] = hold
        return node
    # "remains above N for T" -> numeric_state with `for:` (HA native)
    REMAIN_ABOVE = ("remains_above", "remains_above_or_equal_to",
                    "stays_greater_than", "stays_greater_than_or_equal_to")
    REMAIN_BELOW = ("remains_below", "remains_below_or_equal_to",
                    "stays_less_than", "stays_less_than_or_equal_to")
    if co in REMAIN_ABOVE:
        node = {"kind": "numeric_state", "entities": entities, "above": value,
                "id": trig_id}
        if hold:
            node["for"] = hold
        return node
    if co in REMAIN_BELOW:
        node = {"kind": "numeric_state", "entities": entities, "below": value,
                "id": trig_id}
        if hold:
            node["for"] = hold
        return node

    # ── time ──
    if co == "happens_daily_at" and _is_number(value):
        return {"kind": "time", "at": _minutes_hms(int(value)), "id": trig_id}

    raise NotYetImplemented(f"trigger comparison '{co}' not compiled yet", **ctx)


def _promote(cond: dict, resolver: Resolver, ctx: dict, trig_id=None) -> dict | None:
    """Condition-only piston: webCoRE subscribes to its conditions (promotion,
    webcore-piston.groovy :9242) — the HA equivalent is a trigger built from
    the condition itself. Unpromotable shapes (time windows, variables)
    contribute no trigger; they stay as conditions."""
    co = cond["co"]
    if cond.get("lo_type") == "v":
        return None
    if co in ("is", "is_equal_to"):
        value = cond["value"]
        if _is_number(value):
            return None
        entities = resolver.entities_for_attr(cond["devices"], cond["attr"], ctx)
        return {"kind": "state", "entities": entities,
                "to": resolver.ha_state_value(cond["attr"], value), "id": trig_id}
    if co in ("is_less_than", "is_less_than_or_equal_to"):
        entities = resolver.entities_for_attr(cond["devices"], cond["attr"], ctx)
        return {"kind": "numeric_state", "entities": entities,
                "below": cond["value"], "id": trig_id}
    if co in ("is_greater_than", "is_greater_than_or_equal_to"):
        entities = resolver.entities_for_attr(cond["devices"], cond["attr"], ctx)
        return {"kind": "numeric_state", "entities": entities,
                "above": cond["value"], "id": trig_id}
    return None


# ── actions ─────────────────────────────────────────────────────────────────

def _has_wait(nodes: list) -> bool:
    for n in nodes:
        if n["kind"] == "task" and n["command"] == "wait":
            return True
        if n["kind"] == "if" and (_has_wait(n["then"]) or _has_wait(n["else"])):
            return True
    return False


def _resolve_actions(nodes: list, resolver: Resolver, ctx: dict) -> list:
    out = []
    for n in nodes:
        if n["kind"] == "task":
            if n["command"] == "wait":
                out.append({"kind": "delay", "delay": _delay_hms(n["params"])})
                continue
            if n["command"] == "setLocationMode":
                mode = (n["params"][0] or {}).get("c") if n["params"] else None
                if not isinstance(mode, str):
                    raise NotYetImplemented("setLocationMode with a computed mode", **ctx)
                ent = resolver.system_entity("mode") or                     "input_select.pistoncore_location_mode"
                out.append({"kind": "service", "service": "input_select.select_option",
                            "entities": [ent], "data": {"option": _json_dumps(mode)}})
                continue
            if n["command"] == "sendNotificationToContacts":
                out.append(_send_notification(n["params"], resolver, ctx,
                                              _PISTON.get("cur")))
                continue
            if n["command"] in ("setAlarmSystemStatus", "setHSMStatus"):
                alarm = resolver.system_entity("alarmSystemStatus")
                if not alarm:
                    raise NotYetImplemented(
                        "setting the alarm needs exactly one alarm_control_panel "
                        "in HA (none found, or several — ambiguous)", **ctx)
                status = (n["params"][0] or {}).get("c") if n["params"] else None
                service = resolver.alarm_commands.get(str(status))
                if not service:
                    raise NotYetImplemented(
                        f"alarm status '{status}' has no service mapping "
                        f"(value_maps.json alarm_commands)", **ctx)
                out.append({"kind": "service",
                            "service": f"alarm_control_panel.{service}",
                            "entities": [alarm], "data": None})
                continue
            if n["command"] == "setVariable":
                out.append(_set_variable(n, resolver, ctx))
                continue
            if n["command"] in ("cancelTasks", "cancelPendingTasks"):
                # mode: restart already cancels this automation's pending
                # delays when it retriggers — same effect webCoRE's
                # cancel-pending-tasks has. Nothing to emit.
                continue
            if n["command"] == "sendNotification":
                out.append(_send_notification(n["params"], resolver, ctx, _PISTON.get("cur")))
                continue
            if n["command"] in ("sendPushNotification", "sendSMSNotification",
                                "deviceNotification"):
                out.append(_push_notification(n, resolver, ctx))
                continue
            if n["command"] in ("speak", "playText", "playTextAndResume", "playTextAndRestore"):
                out.append(_speak(n, resolver, ctx))
                continue
            if not n["devices"] or n["command"] in resolver.command_maps.get("_piston_scope", []):
                # piston-scope command (setVariable, log, setState, tiles, ...)
                # — piston state has no YAML equivalent, whatever devices the
                # surrounding action block targets.
                raise NotYetImplemented(
                    f"piston-scope command '{n['command']}' requires PyScript", **ctx)
            entities = resolver.entities_for_command(n["devices"], n["command"], ctx)
            service, data_spec = resolver.service_spec(n["command"], entities[0], ctx)
            data = None
            if data_spec:
                data = {k: _param_value(v, n["params"], ctx) for k, v in data_spec.items()}
            out.append({"kind": "service", "service": service,
                        "entities": entities, "data": data})
        elif n["kind"] == "switch":
            # HA's choose: first matching branch wins, then the sequence exits
            # (HA_YAML_COMPILER_RESEARCH §2). Fall-through is refused upstream.
            lo = n["lo"]
            subject = _switch_subject(lo, resolver, ctx)
            options = []
            for case in n["cases"]:
                value = (case["ro"] or {}).get("c")
                options.append({
                    "conditions": [{"kind": "template", "template":
                                    "{{ " + subject + " == " + _lit(value) + " }}"}],
                    "sequence": _resolve_actions(case["body"], resolver, ctx)})
            out.append({"kind": "choose", "options": options,
                        "default": _resolve_actions(n["default"], resolver, ctx)})
        elif n["kind"] == "loop":
            node = {"kind": "repeat",
                    "body": _resolve_actions(n["body"], resolver, ctx)}
            if n.get("count") is not None:
                node["count"] = int(n["count"])
            elif n["conditions"]:
                key = "until" if n.get("until") else "while"
                node[key] = [_condition(c, resolver, ctx) for c in n["conditions"]]
            else:
                raise NotYetImplemented(
                    "loop with neither a count nor a condition", **ctx)
            out.append(node)
        elif n["kind"] == "stop":
            out.append({"kind": "stop"})
        elif n["kind"] == "if":
            out.append({"kind": "if",
                        "conditions": [_condition(c, resolver, ctx) for c in n["conditions"]],
                        "then": _resolve_actions(n["then"], resolver, ctx),
                        "else": _resolve_actions(n["else"], resolver, ctx)})
        else:
            raise NotYetImplemented(f"action node '{n['kind']}' not compiled yet", **ctx)
    return out


def _set_variable(n: dict, resolver: Resolver, ctx: dict) -> dict:
    """setVariable -> HA's `variables:` action (docs /docs/scripts/, Variables).

    FIDELITY LIMIT, deliberate: HA sequence variables live for ONE run, while
    webCoRE piston variables persist between runs. That difference only bites
    when a piston READS the variable it is writing (an accumulator such as
    `count = count + 1`), so that exact shape is detected and routed to
    PyScript, where the value genuinely persists. Everything else — compute a
    value, use it later in the same run, which is the common case — is
    expressed natively here."""
    params = n["params"]
    p0 = params[0] if params else {}
    name = p0.get("x") or p0.get("c")
    if not name or str(name).startswith("@"):
        raise NotYetImplemented(
            "setting a global variable needs PyScript (its value lives in a "
            "pyscript entity so other pistons can read it)", **ctx)
    if p0.get("xi"):
        raise NotYetImplemented("setting one element of an array needs PyScript", **ctx)
    value_op = params[1] if len(params) > 1 else {"t": "c", "c": ""}
    source = str(value_op.get("e") or value_op.get("x") or "")
    if re.search(r"" + re.escape(str(name)) + r"", source):
        raise NotYetImplemented(
            f"'{name}' is built from its own previous value, which only "
            f"persists between runs under PyScript", **ctx)
    return {"kind": "variables",
            "vars": {str(name): _text_param(value_op, resolver, ctx)}}


def _text_param(op: dict, resolver: Resolver, ctx: dict, piston: dict | None = None) -> str:
    """A user-facing text parameter (notification body, spoken message) as a
    YAML scalar. Constants pass through; anything computed goes through the
    Jinja backend so the YAML band can express it natively instead of routing
    the whole piston to PyScript. Unsupported expressions raise
    NotYetImplemented and the dispatcher falls back, exactly as before."""
    import json as _json
    piston = piston if piston is not None else _PISTON.get("cur")
    if op.get("t") == "c":
        text = op.get("c")
        if isinstance(text, str) and "{" in text:
            jt = _jinja(resolver, ctx, piston)
            # a bare {{ }} is a YAML flow mapping — templates must be quoted
            return _json.dumps("{{ " + jt.transpile_string(text) + " }}")
        return _json.dumps("" if text is None else str(text))
    jt = _jinja(resolver, ctx, piston)
    if op.get("t") == "u":
        # raw user-entered expression text; the trailing ';' is editor noise
        op = {"e": str(op.get("u", "")).rstrip("; ")}
    return _json.dumps("{{ " + jt.transpile_operand(op) + " }}")


def _jinja(resolver: Resolver, ctx: dict, piston: dict | None) -> JinjaTranspiler:
    locals_ = set(getattr(resolver, "local_var_names", set()) or set())
    arrays = {v.get("n") for v in (piston or {}).get("v", [])
              if str(v.get("t", "")).endswith("]")}
    return JinjaTranspiler(locals_, resolver.globals_map, resolver, ctx,
                           "input_select.pistoncore_location_mode",
                           array_vars=arrays)


def _push_notification(n: dict, resolver: Resolver, ctx: dict) -> dict:
    """Push / SMS / device notification -> HA notify. webCoRE's push went to
    the SmartThings/Hubitat app; HA's equivalent is the notify service (the
    companion app registers itself there). notify.notify fans out to every
    configured notifier — the honest general mapping. deviceNotification on a
    media_player is a spoken message, so that routes to Speak instead."""
    import json as _json
    if n["command"] == "deviceNotification" and n["devices"]:
        try:
            ents = resolver.entities_for_command(n["devices"], "speak", ctx)
            if ents and ents[0].startswith("media_player."):
                return _speak(n, resolver, ctx)
        except Exception:
            pass
    p0 = n["params"][0] if n["params"] else {}
    return {"kind": "service", "service": "notify.notify", "entities": [],
            "data": {"message": _text_param(p0, resolver, ctx, n.get("_piston"))}}


def _speak(n: dict, resolver: Resolver, ctx: dict) -> dict:
    """SPEAK_ACTION_SPEC §5.4: tts.speak — target = the engine entity (global
    setting / sole engine), media players + message + cache in data. Constant
    messages only on this band; computed messages route to PyScript."""
    import json as _json
    engine = resolver.system_entity("tts")
    if not engine:
        raise NotYetImplemented(
            "Speak needs a TTS engine — pick one in PistonCore Settings "
            "(several tts.* engines exist in HA)", **ctx)
    if not n["devices"]:
        raise NotYetImplemented("Speak with no speaker devices", **ctx)
    players = resolver.entities_for_command(n["devices"], n["command"], ctx)
    p0 = n["params"][0] if n["params"] else {}
    return {"kind": "service", "service": "tts.speak", "entities": [engine],
            "data": {"media_player_entity_id": players,
                     "message": _text_param(p0, resolver, ctx, n.get("_piston")),
                     "cache": "true"}}


def _send_notification(params: list, resolver: Resolver, ctx: dict,
                       piston: dict | None = None) -> dict:
    """webCoRE 'Send notification' == Hubitat's in-app notification, not push
    — HA's exact equivalent is the notifications panel (persistent
    notification), which exists in every HA with zero setup
    (NOTIFY_ACTION_SPEC: notify.persistent_notification). Push
    (sendPushNotification) stays NotYetImplemented until real mobile targets
    exist. Message must be a constant — expressions need the expression
    engine."""
    import json as _json
    p = params[0] if params else {}
    return {"kind": "service", "service": "notify.persistent_notification",
            "entities": [],
            "data": {"message": _text_param(p, resolver, ctx, piston)}}


def _lit(value) -> str:
    """A webCoRE case value as a Jinja literal."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def _switch_subject(lo: dict, resolver: Resolver, ctx: dict) -> str:
    """The value a switch statement compares its cases against."""
    t = lo.get("t")
    if t == "p" and lo.get("d"):
        entities = resolver.entities_for_attr(lo["d"], lo.get("a"), ctx)
        return "states('" + entities[0] + "')"
    if t == "x" and lo.get("x") == "$currentEventDevice":
        return "trigger.entity_id"
    if t == "v":
        sysent = resolver.system_entity(lo.get("v"))
        if sysent:
            return "states('" + sysent + "')"
    if t == "c":
        return _lit(lo.get("c"))
    raise NotYetImplemented(
        f"switch on operand type '{t}' not compiled yet", **ctx)


def _param_value(token: str, params: list, ctx: dict):
    """$1/$2 (+|transform) tokens from command_maps.json data specs."""
    raw = str(token)
    transform = None
    if "|" in raw:
        raw, tname = raw.split("|", 1)
        transform = _PARAM_TRANSFORMS.get(tname)
        if transform is None:
            raise NotYetImplemented(f"unknown command param transform '{tname}'", **ctx)
    if raw.startswith("$"):
        idx = int(raw[1:]) - 1
        if idx >= len(params):
            raise NotYetImplemented(f"command param {raw} missing", **ctx)
        prm = params[idx]
        value = prm.get("c") if prm.get("c") is not None else prm.get("s")
    else:
        value = raw
    return transform(value) if transform else value


# ── branch emission ─────────────────────────────────────────────────────────

def _emit_branch(br: dict, resolver: Resolver, piston_id: str, piston_name: str,
                 blocks: list, auto_ids: list) -> None:
    ctx = {"piston_id": piston_id, "piston_name": piston_name, "stmt_id": br["stmt_id"]}
    has_wait = _has_wait(br["then"]) or _has_wait(br["else"])
    trig_id = "fire" if has_wait else None

    triggers = []
    cancel_triggers = []
    conditions = []

    if br["kind"] == "timer":
        t = dict(br["timer"])
        t["id"] = trig_id
        triggers.append(t)
    else:
        for trig in br["triggers"]:
            node = _trigger(trig, resolver, ctx, trig_id)
            triggers.append(node)
            if has_wait and br["tcp"] == "c" and node["kind"] == "state" and node.get("to"):
                opposite = resolver.opposite_state(node["to"])
                if opposite is not None:
                    cancel_triggers.append({"kind": "state", "entities": node["entities"],
                                            "to": opposite, "id": "tcp_cancel"})
        if not triggers:
            # condition-only statement -> promote (subscription equivalence)
            for cond in br["conditions"]:
                node = _promote(cond, resolver, ctx, trig_id)
                if node:
                    triggers.append(node)
            if not triggers:
                # nothing here can wake the piston: it is a runnable sequence,
                # not an automation. Signal the script path.
                raise _NoSubscriptions()

    if cancel_triggers:
        conditions.append({"kind": "trigger", "id": "fire"})

    cond_nodes = [_condition(c, resolver, ctx) for c in br["conditions"]]
    then_actions = _resolve_actions(br["then"], resolver, ctx)
    else_actions = _resolve_actions(br["else"], resolver, ctx)

    if else_actions and cond_nodes:
        # else must NOT run on a cancel-trigger pass, so the template
        # conditions move inside an if-action; only the trigger gate stays
        # at automation level.
        actions = [{"kind": "if", "conditions": cond_nodes,
                    "then": then_actions, "else": else_actions}]
    elif else_actions:
        # Trigger-only if WITH an else: webCoRE subscribes to the ATTRIBUTE,
        # so the opposite transition wakes the piston and runs the else —
        # a to:-filtered trigger can't express that (semantic-audit find,
        # 2026-07-19). PyScript band handles it faithfully.
        raise NotYetImplemented(
            "else-branch on a trigger-only if needs any-change wake — "
            "requires PyScript", **ctx)
    else:
        conditions.extend(cond_nodes)
        actions = then_actions

    auto_id = f"pistoncore_{piston_id}_s{br['stmt_id']}"
    auto_ids.append(auto_id)
    block = _env.get_template("automation.yaml.j2").render(
        auto_id=auto_id,
        alias=f"PistonCore: {piston_name} — ${br['stmt_id']}",
        mode="restart" if br["tcp"] == "c" else "queued",
        triggers=triggers + cancel_triggers,
        conditions=conditions,
        actions=actions,
    )
    blocks.append(block)
