"""EMIT (YAML/classic band) — branch IR -> HA automation YAML via the Jinja2
band templates (COMPILER_SPEC §3.3). One automation per top-level if statement
(§2.5 point 4 TCP scoping). TCP-default branches emit mode: restart +
auxiliary cancel-triggers gated by `condition: trigger` — the approved Cave
Motion fixture idiom; `queued` (Jeremy's default) governs where TCP doesn't
force restart."""

from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from .analyze import analyze
from .errors import NotYetImplemented
from .resolve import Resolver
from .routing import pyscript_reasons

_BAND_DIR = Path(__file__).resolve().parent.parent.parent / "templates" / "compiler" / "yaml" / "classic"
_env = Environment(loader=FileSystemLoader(str(_BAND_DIR)), trim_blocks=False, lstrip_blocks=False)

_TEMPLATE_OPS = {"is_less_than": "<", "is_less_than_or_equal_to": "<=",
                 "is_greater_than": ">", "is_greater_than_or_equal_to": ">="}


def _delay_hms(params: list) -> str:
    p = params[0] if params else {}
    n = p.get("c", 0)
    unit = p.get("vt", "s")
    seconds = {"s": n, "m": n * 60, "h": n * 3600}.get(unit, n)
    return f"{seconds // 3600:02d}:{(seconds % 3600) // 60:02d}:{seconds % 60:02d}"


def compile_piston(piston: dict, piston_id: str, piston_name: str,
                   resolution_map: dict, globals_map: dict | None = None) -> dict:
    """Returns {"target": "yaml"|"pyscript", "yaml": str|None, "reasons": [...],
    "auto_ids": [...]}."""
    reasons = pyscript_reasons(piston)
    if reasons:
        return {"target": "pyscript", "yaml": None, "reasons": reasons}

    branches = analyze(piston, piston_id, piston_name)
    resolver = Resolver(piston, resolution_map, globals_map)
    blocks = []
    auto_ids = []
    header = (f"# Generated by PistonCore — piston \"{piston_name}\" ({piston_id})\n"
              f"# DO NOT EDIT — changes are overwritten on recompile. Template band: yaml/classic\n")

    try:
        for br in branches:
            _emit_branch(br, resolver, piston_id, piston_name, blocks, auto_ids)
    except Exception as exc:
        # Half-finished output holds clues to compiler bugs (Jeremy, 2026-07-18:
        # the compiler, not the battle-tested webCoRE JSON, is the likely
        # suspect) — hand back whatever was built before dying so deploy can
        # preserve it in the debug folder.
        exc.partial_yaml = header + "\n".join(blocks) + "\n" if blocks else None
        raise

    return {"target": "yaml", "yaml": header + "\n".join(blocks) + "\n", "reasons": [],
            "auto_ids": auto_ids}


def _emit_branch(br: dict, resolver: Resolver, piston_id: str, piston_name: str,
                 blocks: list, auto_ids: list) -> None:
    ctx = {"piston_id": piston_id, "piston_name": piston_name, "stmt_id": br["stmt_id"]}
    has_wait = any(a["command"] == "wait" for a in br["then"] + br["else"])

    triggers = []
    cancel_triggers = []
    for trig in br["triggers"]:
        if trig["co"] != "changes_to":
            raise NotYetImplemented(
                f"trigger comparison '{trig['co']}' not compiled yet", **ctx)
        entities = resolver.entities_for_attr(trig["devices"], trig["attr"], ctx)
        to_value = resolver.ha_state_value(trig["attr"], trig["value"])
        triggers.append({"entities": entities, "to": to_value,
                         "id": "fire" if has_wait else None})
        if has_wait and br["tcp"] == "c":
            opposite = resolver.opposite_state(to_value)
            if opposite is not None:
                cancel_triggers.append({"entities": entities, "to": opposite,
                                        "id": "tcp_cancel"})

    conditions = []
    if cancel_triggers:
        conditions.append({"kind": "trigger", "id": "fire"})
    for cond in br["conditions"]:
        op = _TEMPLATE_OPS.get(cond["co"])
        if op is None:
            raise NotYetImplemented(
                f"condition comparison '{cond['co']}' not compiled yet", **ctx)
        entities = resolver.entities_for_attr(cond["devices"], cond["attr"], ctx)
        if len(entities) != 1:
            raise NotYetImplemented(
                f"multi-entity numeric condition aggregation not compiled yet", **ctx)
        # fail-closed default: unavailable sensor -> condition false (fixture rule)
        conditions.append({"kind": "template", "template":
            f"{{{{ states('{entities[0]}') | float(default=1.0e9) {op} {cond['value']} }}}}"})

    if br["else"]:
        raise NotYetImplemented("else-branch emission not compiled yet", **ctx)

    actions = []
    for task in br["then"]:
        if task["command"] == "wait":
            actions.append({"kind": "delay", "delay": _delay_hms(task["params"])})
        else:
            entities = resolver.entities_for_command(task["devices"], task["command"], ctx)
            service = resolver.service_for(task["command"], entities[0], ctx)
            actions.append({"kind": "service", "service": service, "entities": entities})

    auto_id = f"pistoncore_{piston_id}_s{br['stmt_id']}"
    auto_ids.append(auto_id)
    block = _env.get_template("automation.yaml.j2").render(
        auto_id=auto_id,
        alias=f"PistonCore: {piston_name} — ${br['stmt_id']}",
        mode="restart" if br["tcp"] == "c" else "queued",
        triggers=triggers + cancel_triggers,
        conditions=conditions,
        actions=actions,
    )
    blocks.append(block)
